on:
  push:
    branches: [ "development", "main" ]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Determine Tag
          id: determine-tag
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            GITHUB_REF_NAME: ${{ github.ref_name }}
          run: |
            if [[ "$GITHUB_REF_NAME" == "development" ]]; then
              TAG="dev"
            else
              LATEST_TAG=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --output=json | jq -r '.imageDetails[].imageTags[]' | grep -E '^v[0-9]+$' | sort -V | tail -n1)
              if [[ -z "$LATEST_TAG" ]]; then
                TAG="v1"
              else
                VERSION_NUMBER=${LATEST_TAG:1}
                NEW_VERSION=$((VERSION_NUMBER + 1))
                TAG="v$NEW_VERSION"
              fi
            fi
            echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            IMAGE_TAG: ${{ env.IMAGE_TAG }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
            
